##  Image 생성 

In [1]:
import numpy as np
import cv2
import os
import sys

### numpy를 이용한 이미지 생성

In [29]:
img1 = np.empty((200, 300), np.uint8)       # grayscale image
img2 = np.zeros((200, 300, 3), np.uint8)    # color image
img3 = np.full((200, 300), 100, np.uint8)   # Fill with 100

mat1 = np.array([[10, 120, 130, 140, 150],
                 [210, 202, 230, 240, 250],
                 [310, 320, 330, 340, 350],
                 [110, 120, 130, 140, 150],
                 [60, 70, 80, 90, 100]]).astype(np.uint8)

mat1[0, 1] = 100    # element at x=1, y=0
mat1[2, :] = 200

print("img1=", img1[0,0])
print("img2=", img2[0,0])
print("img3=", img3[0,0])
print("mat1 = ",  mat1)

cv2.imshow('img1', img1)
cv2.imshow('img2', img2)
cv2.imshow('img3', img3)
cv2.imshow('mat1', mat1)
cv2.waitKey()
cv2.destroyAllWindows()


img1= 80
img2= [0 0 0]
img3= 100
mat1 =  [[100 100 130 140 150]
 [210 202 230 240 250]
 [200 200 200 200 200]
 [110 120 130 140 150]
 [ 60  70  80  90 100]]


### Image copy

In [86]:

img1 = cv2.imread('images/cat.png')
  
if img1 is None:
        print('Image load failed!')
        sys.exit()
        
img2 = img1
img3 = img1.copy()

img1[:50, :50] = (0, 255, 255)  # yellow

cv2.imshow('img1', img1)
cv2.imshow('img2', img2)
cv2.imshow('img3', img3)
cv2.waitKey()
cv2.destroyAllWindows()

### Image 추출 및 연산

In [91]:
img1 = cv2.imread('images/lenna.bmp', cv2.IMREAD_GRAYSCALE)

img2 = img1[200:400, 200:400]
img3 = img1[200:400, 200:400].copy()

img2 +=  40

cv2.imshow('img1', img1)
cv2.imshow('img2', img2)
cv2.imshow('img3', img3)

img4 = cv2.add(img3, 40)  # saturated operation
cv2.imshow('img4', img4)

cv2.waitKey()
cv2.destroyAllWindows()


### Image Flip

In [88]:
#행렬  flip 
mat1 = np.array(np.arange(25).reshape(5, 5))
print('mat1:', mat1)

h, w = mat1.shape[:2]

mat2 = np.zeros(mat1.shape, mat1.dtype)

for j in range(h):
        for i in range(w):
            mat2[j, i] = mat1[h-1-j, i]

print('mat2:')
print(mat2)

# image flip
img1 = cv2.imread('images/cat.png', cv2.IMREAD_GRAYSCALE)
  
if img1 is None:
        print('Image load failed!')
        sys.exit()

h, w = img1.shape[0:2]

img2 = np.zeros(img1.shape, img1.dtype)
print("img1 type=", img1.dtype)
print("img1 shape=", img1.shape)
print("img2 type=", img2.dtype)
print("img2 shape=", img2.shape)


for j in range(h):
           img2[j, :(w-1)] = img1[h-1-j, :(w-1)]

cv2.imshow('img1', img1)
cv2.imshow('img2', img2)

cv2.waitKey()
cv2.destroyAllWindows()

mat1: [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
mat2:
[[20 21 22 23 24]
 [15 16 17 18 19]
 [10 11 12 13 14]
 [ 5  6  7  8  9]
 [ 0  1  2  3  4]]
img1 type= uint8
img1 shape= (192, 256)
img2 type= uint8
img2 shape= (192, 256)
